#!/usr/bin/python3

import hashlib
import subprocess
import shlex
import sqlite3

DRY_RUN = True

VERSION = 3
SCHEMA = f'''
    PRAGMA user_version = {VERSION};
    PRAGMA writable_schema = 0;

    CREATE TABLE step (
        id INTEGER PRIMARY KEY,
        name TEXT NOT NULL,
        priority INTEGER NOT NULL,
        hash TEXT NOT NULL,

        status INTEGER NOT NULL
            DEFAULT 0
            CHECK (0 <= status AND status <= 2),
        pretty_status TEXT AS (CASE
            WHEN status = 0 THEN 'not-started'
            WHEN status = 1 THEN 'in-progress'
            WHEN status = 2 THEN 'complete'
            ELSE 'unknown'
        END)
    ) STRICT;
'''

class Command:
    def __init__(self, name, command, priority, pre_install=None, post_install=None, rollback_command=None, pre_rollback=None, post_rollback=None):
        if pre_install is not None and type(pre_install) is not list:
            pre_install = [pre_install]
        if post_install is not None and type(post_install) is not list:
            post_install = [post_install]
        if pre_rollback is not None and type(pre_rollback) is not list:
            pre_rollback = [pre_rollback]
        if post_rollback is not None and type(post_rollback) is not list:
            post_rollback = [post_rollback]

        self.name = name
        self.command = command
        self.priority = priority
        self.rollback_command = rollback_command
        self.pre_install = pre_install
        self.post_install = post_install
        self.pre_rollback = pre_rollback
        self.post_rollback = post_rollback

        hasher = hashlib.sha256()
        def hash(command):
            if command is None:
                hasher.update(b'')
            else:
                hasher.update(bytes(len(command)))
                for part in command:
                    hasher.update(bytes(part, 'utf-8'))
        hash(command)
        hash(rollback_command)
        hash(pre_install)
        hash(post_install)
        hash(pre_rollback)
        hash(post_rollback)
        self.hash = hasher.hexdigest()

    def declare(self, cursor):
        cursor.execute(
            '''
                INSERT INTO step (name, priority, hash)
                VALUES (?, ?, ?)
            ''',
            (self.name, self.priority, self.hash),
        )

    def enact(self, conn):
        self.record_status(conn, 'in-progress')

        if self.pre_install is not None:
            for command in self.pre_install:
                if type(command) is str:
                    command = shlex.split(command)
                self.execute(command)

        self.execute(self.command)

        if self.post_install is not None:
            for command in self.post_install:
                if type(command) is str:
                    command = shlex.split(command)
                self.execute(command)

        self.record_status(conn, 'complete')

    def rollback(self, conn):
        if self.rollback_command is None:
            raise Exception(f'cannot rollback {self.command}')

        if self.pre_rollback is not None:
            for command in self.pre_rollback:
                self.execute(command)

        self.execute(self.rollback_command)

        if self.post_rollback is not None:
            for command in self.post_rollback:
                self.execute(command)

        self.record_status(conn, 'not-started')

    def execute(self, command):
        print(f'$ {' '.join(command)}')
        if DRY_RUN:
            return
        subprocess.run(command)

    def record_status(self, conn, status):
        statuses = {
            'not-started': 0,
            'in-progress': 1,
            'complete': 2,
        }
        status = statuses[status]
        try:
            cursor = conn.cursor()
            cursor.execute('BEGIN IMMEDIATE')
            cursor.execute(
                '''
                    UPDATE step
                    SET status = ?
                    WHERE hash = ?
                ''',
                (status, self.hash)
            )
            cursor.execute('COMMIT')
        except Exception as ex:
            cursor.execute('ROLLBACK')
            raise ex

PRIORITY_APT = 0
def apt(name, **kwargs):
    return Command(
        name,
        ['sudo', 'apt', 'install', name],
        PRIORITY_APT,
        rollback_command=['sudo', 'apt', 'remove', name],
        **kwargs,
    )

PRIORITY_SNAP = 1
def snap(name, **kwargs):
    return Command(
        name,
        ['sudo', 'snap', 'install', name],
        PRIORITY_SNAP,
        rollback_command=['sudo', 'snap', 'remove', '--purge', name],
        **kwargs
    )

PRIORITY_CLASSIC_SNAP = 2
def classic_snap(name, **kwargs):
    return Command(
        name,
        ['sudo', 'snap', 'install', '--classic', name],
        PRIORITY_CLASSIC_SNAP,
        rollback_command=['sudo', 'snap', 'remove', '--purge', name],
        **kwargs
    )

PRIORITY_CARGO = 3
def cargo(name, **kwargs):
    return Command(
        name,
        ['cargo', 'install', '--locked', name],
        PRIORITY_CARGO,
        rollback_command=['cargo', 'uninstall', name],
        **kwargs
    )

def main():
    tasks = all_tasks()
    conn = ensure_setup('dotfiles.db', tasks)
    cursor = conn.cursor()

    tasks_by_hash = { task.hash: task for task in tasks }

    to_rollback_query = cursor.execute('''
        SELECT hash
        FROM step
        WHERE status = 1
        ORDER BY
            priority ASC,
            name ASC
    ''')
    to_rollback = [ tasks_by_hash[hash] for (hash,) in to_rollback_query ]
    for task in to_rollback:
        task.rollback(conn)

    to_enact_query = cursor.execute('''
        SELECT hash
        FROM step
        WHERE status = 0
        ORDER BY
            priority ASC,
            name ASC
    ''')
    to_enact = [ tasks_by_hash[hash] for (hash,) in to_enact_query ]
    for task in to_enact:
        task.enact(conn)

def all_tasks():
    return [
        apt('curl'),
        apt(
            'fish',
            post_install='sudo chsh -s /usr/bin/fish',
        ),
        apt('gcc'),
        apt('gnome-tweaks'),
        apt('golang-go'),
        apt('luajit'),
        apt('luarocks'),
        apt('make'),
        apt('ripgrep'),
        apt(
            'wezterm',
            pre_install=[
                "curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /etc/apt/keyrings/wezterm-fury.gpg",
                "echo 'deb [signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list",
                "sudo apt update",
            ],
        ),
        snap('brave'),
        snap('discord'),
        snap(
            'obs-studio',
            post_install=[
                "sudo snap connect obs-studio:kernel-module-observe",
                "sudo snap connect obs-studio:screencast-legacy",
                "sudo apt -y install v4l2loopback-dkms v4l2loopback-utils",
                "echo 'options v4l2loopback devices=1 video_nr=13 card_label=\"OBS Virtual Camera\" exclusive_caps=1' | sudo tee /etc/modprobe.d/v4l2loopback.conf",
                "echo \"v4l2loopback\" | sudo tee /etc/modules-load.d/v4l2loopback.conf",
                "sudo modprobe -r v4l2loopback",
                "sudo modprobe v4l2loopback devices=1 video_nr=13 card_label=\"OBS Virtual Camera\" exclusive_caps=1",
            ],
        ),
        snap('steam'),
        snap(
            'yuescript',
            post_install='sudo snap alias yuescript.yue yue'
        ),
        classic_snap('rustup'),
        classic_snap('nvim'),
        cargo('fs-find'),
        cargo('starship'),
        cargo('cargo-nextest'),
    ]

def ensure_setup(db_path, tasks):
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    cursor.executescript('''
        PRAGMA foreign_keys = ON;
    ''')
    
    query = cursor.execute('PRAGMA user_version')
    user_version = cursor.fetchone()[0]
    if user_version == VERSION:
        return conn # Already setup.
    if user_version != 0:
        raise Exception(f'db at {db_path} incompatible, delete then retry')

    try:
        cursor.execute('BEGIN IMMEDIATE')
        cursor.executescript(SCHEMA)
        for task in tasks:
            task.declare(cursor)
        cursor.execute('COMMIT')
    except Exception as ex:
        cursor.execute('ROLLBACK')
        raise ex

    return conn

    # TODO(kcza): add additional commands / extension tables for:
    # - Post-commands
    #   - Setup obs connections
    #   - chsh to fish
    #   - git setup
    # - Pre-commands
    #   - Setup keyrings and apt thingies

if __name__ == '__main__':
    main()
