#!/usr/bin/python3

import os
import sqlite3

VERSION = 2
SCHEMA = f'''
    PRAGMA user_version = {VERSION};
    PRAGMA writable_schema = 0;

    CREATE TABLE package (
        id INTEGER PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        kind INTEGER NOT NULL CHECK (0 <= kind AND kind <= 3),
        pretty_kind TEXT AS (CASE
            WHEN kind = 0 THEN 'apt'
            WHEN kind = 1 THEN 'snap'
            WHEN kind = 2 THEN 'classic-snap'
            WHEN kind = 3 THEN 'crate'
            ELSE 'unknown'
        END),
        status INTEGER NOT NULL
            DEFAULT 0
            CHECK (0 <= status AND status <= 2),
        pretty_status TEXT AS (CASE
            WHEN status = 0 THEN 'not-started'
            WHEN status = 1 THEN 'in-progress'
            WHEN status = 2 THEN 'complete'
            ELSE 'unknown'
        END)
    ) STRICT;

    CREATE TABLE extra_commands (
        command TEXT NOT NULL,
        kind INTEGER NOT NULL CHECK (0 <= kind AND kind <= 1),
        pretty_kind TEXT AS (CASE 
            WHEN kind = 0 THEN 'pre-install'
            WHEN kind = 1 THEN 'post-install'
            ELSE 'unknown'
        END),
        package_id INTEGER NOT NULL,
        sequence_number INTEGER NOT NULL,
        FOREIGN KEY (package_id) REFERENCES package(id)
    ) STRICT;
'''

def main():
    conn = ensure_setup('dotfiles.db')
    cursor = conn.cursor()

    to_rollback_query = cursor.execute('''
        SELECT name, pretty_kind, pretty_status
        FROM package
        WHERE status = 1
        ORDER BY
            kind ASC,
            name ASC
    ''')
    to_rollback = list(to_rollback_query)
    for package in to_rollback:
        rollback(conn, Package(package))

    to_install_query = cursor.execute('''
        SELECT name, pretty_kind, pretty_status
        FROM package
        WHERE status <= 1
        ORDER BY
            kind ASC,
            name ASC
    ''')
    to_install = list(to_install_query)
    for package in to_install:
        install(conn, Package(package))
    print('All packages installed :D')

class Package:
    def __init__(self, raw):
        (name, kind, status) = raw
        self.name = name
        self.kind = kind
        self.status = status

    def __str__(self):
        return self.name

def rollback(conn, package):
    if package.kind == 'apt':
        execute(['sudo', 'apt', 'remove', package.name])
    elif package.kind == 'snap' or package.kind == 'classic-snap':
        execute(['sudo', 'snap', 'remove', '--purge', package.name])
    elif package.kind == 'crate':
        execute(['cargo', 'uninstall', package.name])
    else:
        raise Exception(f'unknown package kind {package.kind}')

    set_status(conn, package, 'not-started')

def install(conn, package):
    set_status(conn, package, 'in-progress')

    cursor = conn.cursor()
    preinstall_commands = cursor.execute('''
        SELECT extra_commands.command, package.name
        FROM extra_commands
        INNER JOIN package ON extra_commands.package_id = package.id
        WHERE extra_commands.kind = 0 AND package.name = ?
        ORDER BY sequence_number
    ''', [package.name])
    for (command, name) in preinstall_commands:
        execute([command])

    if package.kind == 'apt':
        execute(['sudo', 'apt', 'install', package.name])
    elif package.kind == 'snap':
        execute(['sudo', 'snap', 'install', package.name])
    elif package.kind == 'classic-snap':
        execute(['sudo', 'snap', 'install', package.name, '--classic'])
    elif package.kind == 'crate':
        execute(['cargo', 'install', package.name, '--locked'])
    else:
        raise Exception(f'unknown package kind {package.kind}')

    preinstall_commands = cursor.execute('''
        SELECT extra_commands.command, package.name
        FROM extra_commands
        INNER JOIN package ON extra_commands.package_id = package.id
        WHERE extra_commands.kind = 1 AND package.name = ?
        ORDER BY sequence_number
    ''', [package.name])
    for (command, name) in preinstall_commands:
        execute([command])

    set_status(conn, package, 'complete')

statuses = {
    'not-started': 0,
    'in-progress': 1,
    'complete': 2,
}
def set_status(conn, package, status):
    status = statuses[status]
    try:
        cursor = conn.cursor()
        cursor.execute('BEGIN IMMEDIATE')
        cursor.execute(
            '''
                UPDATE package
                SET status = ?
                WHERE name = ?
            ''',
            (status, package.name)
        )
        cursor.execute('COMMIT')
    except Exception as ex:
        cursor.execute('ROLLBACK')
        raise ex

def execute(cmd, dry_run=True):
    print(f'$ {' '.join(cmd)}')
    if dry_run:
        return
    subprocess.run(cmd)

def ensure_setup(db_path):
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    cursor.executescript('''
        PRAGMA foreign_keys = ON;
    ''')
    
    query = cursor.execute('PRAGMA user_version')
    user_version = cursor.fetchone()[0]
    if user_version == VERSION:
        return conn # Already setup.
    if user_version != 0:
        raise Exception(f'db at {db_path} incompatible, delete then retry')

    try:
        cursor.execute('BEGIN IMMEDIATE')
        cursor.executescript(SCHEMA)
        insert_data(cursor)
        cursor.execute('COMMIT')
    except Exception as ex:
        cursor.execute('ROLLBACK')
        raise ex

    # TODO(kcza): add additional commands / extension tables for:
    # - Post-commands
    #   - Setup obs connections
    #   - chsh to fish
    #   - git setup
    # - Pre-commands
    #   - Setup keyrings and apt thingies
    return conn

def insert_data(cursor):
    packages = [{
        'name': 'curl',
        'kind': 0,
    }, {
        'name': 'fish',
        'kind': 0,
        'post-install': [
            'sudo chsh -s /usr/bin/fish',
        ],
    }, {
        'name': 'gcc',
        'kind': 0,
    }, {
        'name': 'gnome-tweaks',
        'kind': 0,
    }, {
        'name': 'golang-go',
        'kind': 0,
    }, {
        'name': 'luajit',
        'kind': 0,
    }, {
        'name': 'luarocks',
        'kind': 0,
    }, {
        'name': 'make',
        'kind': 0,
    }, {
        'name': 'ripgrep',
        'kind': 0,
    }, {
        'name': 'wezterm',
        'kind': 0,
        'pre-install': [
            "curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /etc/apt/keyrings/wezterm-fury.gpg",
            "echo 'deb [signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list",
            "sudo apt update",
        ],
    }, {
        'name': 'brave',
        'kind': 1,
    }, {
        'name': 'discord',
        'kind': 1,
    }, {
        'name': 'obs-studio',
        'kind': 1,
        'post-install': [
            "sudo snap connect obs-studio:kernel-module-observe",
            "sudo snap connect obs-studio:screencast-legacy",
            "sudo apt -y install v4l2loopback-dkms v4l2loopback-utils",
            "echo 'options v4l2loopback devices=1 video_nr=13 card_label=\"OBS Virtual Camera\" exclusive_caps=1' | sudo tee /etc/modprobe.d/v4l2loopback.conf",
            "echo \"v4l2loopback\" | sudo tee /etc/modules-load.d/v4l2loopback.conf",
            "sudo modprobe -r v4l2loopback",
            "sudo modprobe v4l2loopback devices=1 video_nr=13 card_label=\"OBS Virtual Camera\" exclusive_caps=1",
        ]
    }, {
        'name': 'steam',
        'kind': 1,
    }, {
        'name': 'nvim',
        'kind': 2,
    }, {
        'name': 'rustup',
        'kind': 2,
    }, {
        'name': 'yuescript',
        'kind': 2,
    }, {
        'name': 'fd-find',
        'kind': 3,
    }, {
        'name': 'starship',
        'kind': 3,
    }, {
        'name': 'cargo-nextest',
        'kind': 3,
    }]
    for spec in packages:
        cursor.execute(
            '''
                INSERT INTO package (name, kind) VALUES (?, ?)
            ''',
            (spec['name'], spec['kind']),
        )
        if 'pre-install' in spec:
            for (sequence_number, command) in enumerate(spec['pre-install']):
                cursor.execute(
                    '''
                        INSERT INTO extra_commands (command, kind, package_id, sequence_number)
                        SELECT ?, 0, package.id, ?
                        FROM package
                        WHERE
                            package.name = ?
                    ''',
                    (command, 1+sequence_number, spec['name']),
                )
        if 'post-install' in spec:
            for (sequence_number, command) in enumerate(spec['post-install']):
                cursor.execute(
                    '''
                        INSERT INTO extra_commands (command, kind, package_id, sequence_number)
                        SELECT ?, 1, package.id, ?
                        FROM package
                        WHERE
                            package.name = ?
                    ''',
                    (command, 1+sequence_number, spec['name']),
                )

if __name__ == '__main__':
    main()

# set -ve
#
# sudo apt install ripgrep
# sudo snap install yuescript --classic
# sudo snap alias yuescript.yue yue
#
# sudo snap install rustup --classic
# rustup toolchain install stable
# cargo install cargo-nextest
#
# sudo snap install nvim --classic
# cargo install fd-find
# sudo apt install luajit luarocks
#
# sudo snap install obs-studio
# sudo snap connect obs-studio:kernel-module-observe
# sudo snap connect obs-studio:screencast-legacy
# sudo apt -y install v4l2loopback-dkms v4l2loopback-utils
# echo 'options v4l2loopback devices=1 video_nr=13 card_label="OBS Virtual Camera" exclusive_caps=1' | sudo tee /etc/modprobe.d/v4l2loopback.conf
# echo "v4l2loopback" | sudo tee /etc/modules-load.d/v4l2loopback.conf
# sudo modprobe -r v4l2loopback
# sudo modprobe v4l2loopback devices=1 video_nr=13 card_label="OBS Virtual Camera" exclusive_caps=1
#
# sudo snap install brave
