[mattermost]
host = chat.canonical.com
#team = the default team

# Set with: snap run --shell matterhorn -c 'secret-tool store --label="$SNAP_NAME" $SNAP_NAME token
tokencmd = secret-tool lookup matterhorn token

urlOpenCommand = xdg-open
activityNotifyCommand = /snap/matterhorn/current/app/notification-scripts/notify

showTypingIndicator = True

enableAspell = True
#aspellDictionary = "en"
channelSelectCaseInsensitive = False
channelListOrientation = right
sendTypingNotifications = True

themeCustomizationFile = theme.ini
